service: serverless-fullstack-react-app

frameworkVersion: ">=4.0.0"

custom:
  # Stage-specific CORS origin (single value or wildcard)
  corsOrigin:
    dev: '*'  # Allow all origins for dev (use specific domain in prod)
    prod: 'https://d3f3z8uaga4kw3.cloudfront.net'

  # Get current stage's CORS origin
  currentCorsOrigin: ${self:custom.corsOrigin.${opt:stage, self:provider.stage}, self:custom.corsOrigin.dev}

package:
  individually: true  # Package each function separately for smaller deployments
  patterns:
    - '!client/**'
    - '!.github/**'
    - '!.git/**'
    - '!.next/**'
    - '!out/**'
    - '!README.md'
    - '!*.md'
    - '!.gitignore'
    - '!.env*'
    - '!coverage/**'
    - '!test/**'
    - '!tests/**'
    - '!**/*.test.js'
    - '!jest.config.js'
    - '!.eslintrc*'
    - '!.prettierrc*'
    - 'src/**'
    - 'node_modules/**'
    - 'package.json'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    MAX_TODO_LENGTH: 500
  apiGateway:
    minimumCompressionSize: 1024  # Compress responses > 1KB
    usagePlan:
      throttle:
        burstLimit: 200      # Maximum concurrent requests
        rateLimit: 100       # Requests per second (steady state)
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: src/functions/create.create
    events:
      - http:
          path: todos
          method: post
          cors:
            origin: ${self:custom.currentCorsOrigin}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: false

  list:
    handler: src/functions/list.list
    events:
      - http:
          path: todos
          method: get
          cors:
            origin: ${self:custom.currentCorsOrigin}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: false

  get:
    handler: src/functions/get.get
    events:
      - http:
          path: todos/{id}
          method: get
          cors:
            origin: ${self:custom.currentCorsOrigin}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: false

  update:
    handler: src/functions/update.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors:
            origin: ${self:custom.currentCorsOrigin}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: false

  delete:
    handler: src/functions/delete.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors:
            origin: ${self:custom.currentCorsOrigin}
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
            allowCredentials: false

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

    # S3 Bucket for Frontend Hosting
    FrontendBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-frontend-${opt:stage, self:provider.stage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    # S3 Bucket Policy
    FrontendBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref FrontendBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: !Sub '${FrontendBucket.Arn}/*'

    # CloudFront Distribution
    FrontendDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
          Origins:
            - Id: S3Origin
              DomainName: !GetAtt FrontendBucket.DomainName
              S3OriginConfig:
                OriginAccessIdentity: ''
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            Compress: true

  Outputs:
    FrontendURL:
      Description: CloudFront Distribution URL
      Value: !Sub 'https://${FrontendDistribution.DomainName}'

    FrontendBucketName:
      Description: S3 Bucket Name
      Value: !Ref FrontendBucket
