name: Test API

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Test API
      run: |
        echo "Getting API endpoint..."
        npx serverless info --verbose
        ENDPOINT=$(npx serverless info --verbose 2>&1 | grep -E "https://.*\.execute-api\..*\.amazonaws\.com/[^/]+" | grep -oE "https://[^/]+/[^/]+" | head -1)
        echo "Endpoint found: $ENDPOINT"
        if [ -z "$ENDPOINT" ]; then
          echo "ERROR: Could not extract API endpoint"
          exit 1
        fi
        chmod +x ./utils/test-api.sh
        API_ENDPOINT=$ENDPOINT ./utils/test-api.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}