name: Test API

on:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    env:
      STAGE: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run Integration Tests
      run: |
        echo "Getting API endpoint for stage: ${{ env.STAGE }}"
        npx serverless info --stage ${{ env.STAGE }} --verbose
        ENDPOINT=$(npx serverless info --stage ${{ env.STAGE }} --verbose 2>&1 | grep -E "https://.*\.execute-api\..*\.amazonaws\.com/[^/]+" | grep -oE "https://[^/]+/[^/]+" | head -1)
        echo "Endpoint found: $ENDPOINT"
        if [ -z "$ENDPOINT" ]; then
          echo "ERROR: Could not extract API endpoint"
          exit 1
        fi
        chmod +x ./utils/*.sh
        API_ENDPOINT=$ENDPOINT ./utils/run-all-tests.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
